name: pull request check

on:
  pull_request

jobs:
  check:
    if: github.repository == 'kaleidot725/ScrcpyHub'
    name: Check pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: run ktlintCheck
        run: |
          ./gradlew --continue ktlintCheck
        continue-on-error: true
      - name: run test
        run: |
          ./gradlew test
      - name: run danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install danger danger-checkstyle_format danger-android_lint danger-junit
          danger
